// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorLigaFutbol.API.Migrations
{
    [DbContext(typeof(GestorLigaFutbolAPIContext))]
    [Migration("20261002220941_V001")]
    partial class V001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorLigaFutbol.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFundacion")
                        .HasColumnType("integer")
                        .HasColumnName("anio_fundacion");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ciudad");

                    b.Property<int>("LigaId")
                        .HasColumnType("integer")
                        .HasColumnName("liga_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.ToTable("equipos");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estadios");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Gol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jugador_id");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer")
                        .HasColumnName("partido_id");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("goles");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<int>("DorsalCamisa")
                        .HasColumnType("integer")
                        .HasColumnName("dorsal_camisa");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer")
                        .HasColumnName("equipo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("posicion");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("jugadores");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pais");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("varchar(22)")
                        .HasColumnName("temporada");

                    b.HasKey("Id");

                    b.ToTable("ligas");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipo_local_id");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("equipo_visitante_id");

                    b.Property<int>("EstadioId")
                        .HasColumnType("integer")
                        .HasColumnName("estadio_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("integer")
                        .HasColumnName("goles_local");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("goles_visitante");

                    b.Property<bool>("Jugado")
                        .HasColumnType("boolean")
                        .HasColumnName("jugado");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("EstadioId");

                    b.ToTable("partidos");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Equipo", b =>
                {
                    b.HasOne("GestorLigaFutbol.Models.Liga", "liga")
                        .WithMany("Equipos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("liga");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Gol", b =>
                {
                    b.HasOne("GestorLigaFutbol.Models.Jugador", "jugador")
                        .WithMany("Goles")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorLigaFutbol.Models.Partido", "partido")
                        .WithMany("Goles")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("jugador");

                    b.Navigation("partido");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Jugador", b =>
                {
                    b.HasOne("GestorLigaFutbol.Models.Equipo", "equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipo");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Partido", b =>
                {
                    b.HasOne("GestorLigaFutbol.Models.Equipo", "equipoLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorLigaFutbol.Models.Equipo", "equipoVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorLigaFutbol.Models.Estadio", "estadio")
                        .WithMany("Partidos")
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipoLocal");

                    b.Navigation("equipoVisitante");

                    b.Navigation("estadio");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Estadio", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Jugador", b =>
                {
                    b.Navigation("Goles");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Liga", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("GestorLigaFutbol.Models.Partido", b =>
                {
                    b.Navigation("Goles");
                });
#pragma warning restore 612, 618
        }
    }
}
